# GET all persons
# 200
GET https://phonebook-18ex.onrender.com/api/persons

###

# POST new person
# 201
POST https://phonebook-18ex.onrender.com/api/persons
Content-Type: application/json

{
    "content": "Matti Meikäläinen",
    "number": "045-987654"
}

###

# GET all persons again to confirm
# 200
GET https://phonebook-18ex.onrender.com/api/persons

###

# POST same person again to test 
# 400 "error": "name must be unique"
POST https://phonebook-18ex.onrender.com/api/persons
Content-Type: application/json

{
    "content": "Matti Meikäläinen",
    "number": "045-987654"
}

###

# POST person with no number. 
# 400 "error": "name or number missing"
POST https://phonebook-18ex.onrender.com/api/persons
Content-Type: application/json

{
    "content": "Matti Meikäläinen"
}

###

# POST person with no number. 
# 400 "error": "name or number missing"
POST https://phonebook-18ex.onrender.com/api/persons
Content-Type: application/json

{
    "number": "045-123456"
}

###