# GET all persons
GET https://phonebook-18ex.onrender.com/api/persons

###

# DELETE one
DELETE https://phonebook-18ex.onrender.com/api/persons/1

###

# GET again to confirm deletion
GET https://phonebook-18ex.onrender.com/api/persons

###

# DELETE one again. Should return 404
DELETE https://phonebook-18ex.onrender.com/api/persons/1

###